---
language: python

python: "2.7"

branches:
  only:
  - master

addons:
  apt:
    packages:
    - python-pip

install:
  - pip install ansible-lint

script:
  - make lint

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  email:
    on_success: change
    on_failure: change
