---
language: python
python: "2.7"

addons:
  apt:
    packages:
    - python-pip

install:
  - "whoami"
  - "pip install -r requirements.txt"
  - "echo 'roles_path = ../' >> ansible.cfg"
  - "mkdir -p /etc/ansible/roles"

script:
  - make lint
  - ansible-playbook tests/machine.yml -i tests/inventory --become

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
