- hosts: all
  roles:
    - role: workstation
      apps:
        chrome:
        virtualbox:
        atom:
          packages:
            - atom-beautify
            - build
            - file-icons
            - git-plus
            - highlight-selected
            - linter
            - minimap
            - minimap-highlight-selected
            - script
            - tool-bar
